### PR TITLE
Fix preview failed when .net9-prerelease sdk is installed

### LINKED ISSUE #120: Extension does not work when .NET 9 Previews is installed
### Describe the bug

Previewing & Auto-Complete stops working when .NET 9 is installed.

### To Reproduce

Install any .NET 9 Previews.

### Avalonia for VS Code

0.0.31

### Avalonia version

11.0.4 - 11.0.10

### VS Code version

1.85.2

### Relevant log output

```shell
[AvaloniaTeam.vscode-avalonia]Unexpected token 'E', "Error pars"... is not valid JSON
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
mainThreadExtensionService.ts:82 SyntaxError: Unexpected token 'E', "Error pars"... is not valid JSON
    at JSON.parse (<anonymous>)
    at updateSolutionModel (c:\Users\tinta\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\out\services\solutionParser.js:62:23)
    at ChildProcess.<anonymous> (c:\Users\tinta\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\out\services\solutionParser.js:108:17)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.onexit (node:internal/child_process:302:5)
```

### Additional context

For now, the only way to get it working again, is to uninstall .NET 9, which may require a reboot.

### PR DESCRIPTION
**Pull request by zhangchaoza**
Fix #120

### CODE REVIEW

**Comment by microhobby** [comment]
Hey @zhangchaoza I'm not used to git submodules, but this should not have "automagically" be added here since wit was merged in the other repo?

**Comment by zhangchaoza** [comment]
> Hey @zhangchaoza I'm not used to git submodules, but this should not have "automagically" be added here since it was merged in the other repo?

Other repo's mergers are not automatically merged here. It still needs to be updated manually.

**Comment by heartacker** [comment]
yes, that fix is merged in their repo, we need to update the submodule to the version. that is this

**Review by maxkatz6 — APPROVED** [review]
Thanks!

**Comment by auxym** [comment]
The latest version available to install from the vs code marketplace is 0.0.31, which was released back in February (https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.vscode-avalonia). Therefore I believe it does not contain this fix.

Could you please release a new version of the extension to the marketplace? I created a new Avalonia project based on the avalonia.app template with net9.0, and it doesn't seem to work with the extension

**Comment by heartacker** [comment]
@maxkatz6

**Pull request merged**
