### PR TITLE
Fix buffer index crashes

### PR DESCRIPTION
**Pull request by jojorne**
Notes
* Position.Line doesn't take into account trimmed lines.
* It appears that the axaml doesn't care about the line feed.

### CODE REVIEW

**Comment by jojorne** [comment]
But I think something like this would be better, especially if you want to reuse `GetLine`.

```csharp
namespace AvaloniaLanguageServer.Services;

public sealed class Buffer
{

    public string? GetTextTillLine(Position position)
    {
        var text = string.Join("\n", _lines[..position.Line]);
        var line = GetLine(position)[..position.Character];
        return $"{text}\n{line}";
    }

    public string? GetLine(Position position)
    {
        return _lines[position.Line];
    }

    public string GetText()
    {
        return string.Join("\n", _lines);
    }

    public Buffer(string text)
    {
        _lines = text.Split(separator, StringSplitOptions.None);
    }
    
    private readonly string[] _lines;
    private static readonly string[] separator = { "\n", "\r\n" };
}

```

**Comment by microhobby** [comment]
Hey @prashantvc this should fix #110 and #113

**Comment by microhobby** [comment]
LGTM, thanks for the contribution @jojorne !

**Comment by jojorne** [comment]
Any idea when the vscode extension will be updated? 🤔
It's just that this project seems abandoned... 😅

**Comment by l0hn** [comment]
Is there a plan to release an update to the extension?

**Pull request merged**
