### PR TITLE
feat(vscode-avalonia): prompt users to choose a solution file if workspace contains multiple

### LINKED ISSUE #101: `getSolutionFile` silently selects the first solution when multiple are found
### Describe the bug

```ts
async function getSolutionFile(): Promise<string | undefined> {
	const filePattern = "**/*.sln";
	const files = await vscode.workspace.findFiles(filePattern);

	if (files.length > 0) {
		return files[0].fsPath;
	}

	return vscode.workspace.workspaceFolders?.[0].uri.fsPath;
}
```
This function may automatically select the "incorrect" solution file when multiple are found in the workspace.
Now, the user is given the choice of which solution file we read.

I've [committed a fix](https://github.com/BinToss/AvaloniaUI.AvaloniaVSCode/commit/c42184f0f434dea48c082f9fa99fef89a08e119d), but I still need to create a separate branch and open a PR.

### To Reproduce

<h />

### Avalonia for VS Code

v0.0.17-v0.0.29

### Avalonia version

_No response_

### VS Code version

_No response_

### Relevant log output

```shell
> irrelevant
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BinToss**
Resolves #101 

Note: commented code will not work until `tc39/proposal-explicit-resource-management` is formally part of ES. The commented code can be compiled with ESNext, but won't run in supported in VSCode <= v1.86.1

### CODE REVIEW

**Comment by prashantvc** [comment]
Can you elaborate how this feature works please? I mean as a avalonia developer how will use this feature

**Comment by BinToss** [comment]
Currently, if the workspace contains several Solution files, the extension selects the first one it finds (SolutionA) and passes it to the SolutionParser.
There's a chance SolutionA does not have any WinExe projects by design.
However, a WinExe project may exist in SolutionB, SolutionC, et cetera.

This change allows the user to choose which Solution file should be passed to SolutionParser.

----

On that note, perhaps _every_ solution file should be parsed and filtered for Solutions which include the current document. Only then should the user be prompted.

**Comment by prashantvc** [comment]
Sounds goo. Could you fix the review comments? I will merge once you do it :)

**Comment by BinToss** [comment]
I don't see any review comments to resolve.

**Comment by BinToss** [comment]
I accidentally deleted the wrong branch and I'm unable to re-open the pull request. I have to create a new one...

**Comment by BinToss** [comment]
w

**Pull request closed without merging**
